### ISSUE TITLE
Geojson gen script hits query limit for the geocoding API

### ISSUE THREAD

**Issue by ETNOL** [stevekinney/pizza#153]
The generator is tapping out the API rate limit after just a few calls. I thought it was the short-term request limit but increasing the sleep amount didn't seem to help. I guess its possible some other services are using the same API key at this moment? 

Google reference to their usage limits
https://developers.google.com/maps/faq#usage_exceed

**Comment by defel** [comment]
You can generate an API-Key in the Google-Cloud Console: https://console.cloud.google.com/google/maps-apis/apis/geocoding-backend.googleapis.com/credentials

Then configure Geocode:

```
Geocoder.configure(
       lookup: :google,
       api_key: "your-api-key-here..."
)
```
But then an other error is shown: 

```ruby
Google API error: request denied.
Traceback (most recent call last):
	6: from docs/map_readme.rb:56:in `<main>'
	5: from docs/map_readme.rb:56:in `each'
	4: from docs/map_readme.rb:57:in `block in <main>'
	3: from /usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `each'
	2: from /usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `upto'
	1: from /usr/lib/ruby/gems/2.5.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190:in `block in each'
docs/map_readme.rb:63:in `block (2 levels) in <main>': undefined method `longitude' for nil:NilClass (NoMethodError)
```
