### ISSUE TITLE
Chicago pizza…

### ISSUE THREAD

**Issue by ughitsaaron** [stevekinney/pizza#17]
Is it actually pizza?

**Comment by nelsonpecora** [comment]
I would contend that pizza should be delineated by type (or at least have the type attached to the name somewhere). These are the types I can think of off the top of my head:
- New York Style
- Chicago Style
- Italian (North vs. South delineation, maybe?)
- Californian (a variation on New York Style, [Cheese Board in Berkeley, CA is a good example](http://cheeseboardcollective.coop/))

I imagine there are others.

**Comment by dcousineau** [comment]
http://en.wikipedia.org/wiki/Casserole

**Comment by ughitsaaron** [comment]
@dcousineau :+1:

**Comment by nelsonpecora** [comment]
@aptkf what's your opinion of [Detroit-style pizza](http://en.wikipedia.org/wiki/Detroit-style_pizza)?

**Comment by ughitsaaron** [comment]
@yoshokatana It's pretty comparable to a [Sicilian-style pizza](http://en.wikipedia.org/wiki/Sicilian_pizza) -- but it's not particularly good. 😕

**Comment by jsocol** [comment]
Detroit style is definitely a unique thing, and it's not quite a casserole, it's almost more like some kind of topped baked good.

**Comment by stevekinney** [comment]
My view on this is that submissions should follow the principle of least surprise. If I went to some place thinking it was traditional pizza and it was actually deep dish, I would be surprised (and personally, I'd be unhappy—but that's just like my opinion). But, if I received Sicilian, that would be totally cool. But sometimes, you want deep dish—and we should provide the service of pointing you in the direction of some awesome deep dish, right?

So, we have two solutions: a separate repository (yuck) or just a separate Markdown file for Chicago pizza (yay). I'm totally open to your thoughts/opinions/outrage.

See also: #58.

**Comment by jsocol** [comment]
I vote for the separate Markdown file for Chicago-styles.

**Comment by dbeg** [comment]
I already created a [deep dish pizza](https://github.com/dbeg/deep-dish-pizza) repo and started populating it, but would gladly roll it into this project if the consensus was to keep both connected.

**Comment by nelsonpecora** [comment]
:+1: separate file, or even just a tag (since there are a lot of different kinds of pizza that we haven't even covered in this conversation)

**Comment by nealrs** [comment]
DD pizza is.... not real pizza (and _certainly_ not apizza) - :+1: for keeping it separate.
also, thank you @stevekinney for making this a thing.

**Comment by mikedao** [comment]
@nealrs It's not pizza, it's a casserole.

**Comment by jsocol** [comment]
^^^ +100. A delicious casserole of meat cheese and tomato sauce, but s casserole nonetheless. 

##

**Comment by nealrs** [comment]
Agree.

**Comment by stevekinney** [comment]
I also agree.

**Comment by ughitsaaron** [comment]
💯
