### ISSUE TITLE
Should the property keys 'City' and 'Pizzeria' be lowercase like the rest of the keys?

### ISSUE THREAD

**Issue by alanbsmith** [stevekinney/pizza#79]
The issue can be found [on these lines](https://github.com/stevekinney/pizza/blob/master/map_readme.rb#L33-L34).
I think they probably should to be uniform (and consistent with JSON). I'm working on a search API endpoint, and it would be really helpful for this to be consistent. I'm happy to fix it myself.

Is there a geojson sort of reason we are doing it this way? Wanted to make sure before messing with it.

@cluhring or @aptkf, looks like those lines are yours. Any reason I shouldn't lowercase them?

**Comment by ughitsaaron** [comment]
Go for it! Thanks for your work, @alanbsmith!

**Comment by alanbsmith** [comment]
Thanks! will do.

**Comment by alanbsmith** [comment]
this is now resolved with commit: 46cf57d3e534a10b361146e972cf8bc2a3f75739
